'\" t
.\"     Title: FLARE
.\"    Author: Jan-Hendrik Peters <hennr@hennr.name>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 12/26/2011
.\"    Manual: flare User Manual
.\"    Source: flare
.\"  Language: English
.\"
.TH "FLARE" "6" "12/26/2011" "flare" "flare User Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
flare \- diablo like rpg game
.SH "DESCRIPTION"
.PP
This manual page documents briefly the game flare and the files it uses\&.
.PP
\fBflare\fR
is a diablo like rpg game\&.
.SH "FILES"
.PP
settings\&.txt
.RS 4
flare does not have a settings dialogue yet\&. You can manipulate flare\*(Aqs settings in the settings\&.txt instead\&. It is located in one of the following paths: $XDG_CONFIG_HOME/flare $HOME/\&.config/flare \&./config
.RE
.PP
keybindings\&.txt
.RS 4
You can manipulate flare\*(Aqs default key bindings in this file\&. It is located in one of the following paths: $XDG_CONFIG_HOME/flare $HOME/\&.config/flare \&./config
.RE
.PP
save[0\-9]{?}\&.txt
.RS 4
Savegames are simple txt files in flare\&. You can find them at one of these places: $XDG_DATA_HOME/flare $HOME/\&.local/share/flare \&./saves If permissions are correct, the game is automatically saved when you exit\&.
.RE
.SH "ENVIONMENT"
.PP
\fBXDG_CONFIG_HOME, $XDG_DATA_HOME\fR
.RS 4
flare follows the XDG stanard, see FILES section above\&.
.RE
.SH "BUGS"
.PP
If you should find a bug in flare, please report it at the official BTS at:
\m[blue]\fB\%https://github.com/clintbellanger/flare/issues\fR\m[]\&.
.SH "AUTHOR"
.PP
\fBJan\-Hendrik Peters\fR <\&hennr@hennr\&.name\&>
.RS 4
Wrote this manpage for the Debian system\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2011 Jan-Hendrik Peters
.br
.PP
This manual page was written for the Debian system (and may be used by others)\&.
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 or (at your option) any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
/usr/share/common\-licenses/GPL\&.
.sp
